name: Deploy Documentation
on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git revision dates
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Set up Python virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip wheel
          pip install -r docs/requirements.txt
        
      - name: Build documentation
        run: |
          source .venv/bin/activate
          cd docs
          mkdocs build --clean --verbose
          
      - name: Deploy documentation
        if: success()
        run: |
          source .venv/bin/activate
          cd docs
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          mkdocs gh-deploy --force --config-file mkdocs.yml --remote-branch gh-pages
